# Generated by Django 4.2.7 on 2023-11-13 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='canciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('pista', models.FileField(default='audio/default.mp3', upload_to='audio/')),
                ('date', models.DateField()),
            ],
        ),
    ]
