# Generated by Django 4.2.7 on 2023-11-21 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='canciones',
            options={'ordering': ['-date_singles']},
        ),
        migrations.RenameField(
            model_name='canciones',
            old_name='date',
            new_name='date_singles',
        ),
    ]
