# Generated by Django 4.2.7 on 2023-11-21 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-date_post']},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='date',
            new_name='date_post',
        ),
    ]
